dist: xenial
jobs:
  include:
    - stage: Run tests and upload results to TestRail
      language: python
      python: 3.9-dev
      addons:
        chrome: stable
      script:
        - mvn clean compile test
      after_script:
        - pip install trcli
        - trcli -y
           -h https://INSTANCE.testrail.io/
           --project "PROJECT NAME"
           -u USER_EMAIL
           -p PASSWORD
           parse_junit
           --title "Automated Tests from Travis workflow"
           --run-description $TRAVIS_JOB_WEB_URL
           -f "./target/surefire-reports/TEST-TestSuite.xml"
