dist: xenial
jobs:
  include:
    - stage: Run tests and upload results to TestRail
      language: python
      python: 3.9-dev
      addons:
        chrome: stable
      script:
        - mvn clean compile test
      after_script:
        - >
        if[ -f "./target/surefire-reports/TEST-TestSuite.xml" ] then
          echo "JUnit report file found: ./target/surefire-reports/TEST-TestSuite.xml";
        else
          echo "JUnit report file not found: ./target/surefire-reports/TEST-TestSuite.xml";
          exit 1;
        fi
