dist: xenial

jobs:
  include:
    - stage: Run tests and upload results
      language: python
      python: 3.9
      addons:
        chrome: stable
      script:
        - mvn clean compile test
      after_script:
        - >
          if [ -f "./target/surefire-reports/TEST-TestSuite.xml" ]; then
            echo "JUnit report file found: ./target/surefire-reports/TEST-TestSuite.xml";
            curl -X POST $API_URL -H "x-api-key:$API_KEY" -F "file=@./target/surefire-reports/TEST-TestSuite.xml";
          else
            echo "JUnit report file not found: ./target/surefire-reports/TEST-TestSuite.xml";
            exit 1;
          fi
